CREATE TABLE User (
    id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
    name VARCHAR(50),
    email VARCHAR(50),
    pass VARCHAR(50)
);

CREATE TABLE blog  (
    blog_id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
    user_fk INTEGER,
    title VARCHAR(50),
    content VARCHAR(1000),
    category VARCHAR(50),
    FOREIGN KEY (user_fk) REFERENCES User(id)
    ON DELETE CASCADE  ON UPDATE NO ACTION
);
